SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 10
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE = 3.0  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 50
PLAYER_SPEED = 50
PLAYER_SHOOT_SPEED = 400

SHOT_RADIUS = 4
